import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { utils } from "@worldcoin/id";
import { AppProps } from "@worldcoin/id";
import { useEffect } from "react";

const WorldIDWidget = dynamic(
  () => import("@worldcoin/id").then((mod) => mod.WorldIDWidget),
  { ssr: false }
);

const widgetProps: AppProps = {
  action_id: "wid_staging_PCNQeDC5CX",
  signal: "user-id-1",
  enable_telemetry: true,
  app_name: "candyApp",
  signal_description: "Receive initial airdrop April 2022",
  theme: "light",
  debug: true,
  on_success: (result) => console.log(result),
  on_error: ({ code, detail }) => console.log({ code, detail }),
  on_init_success: () => console.log("Init successful"),
  on_init_error: (error) => console.log("Error while initialization World ID", error),
};

const Home: NextPage = () => {
  useEffect(() => {
    console.log("Random Number from utils: ", utils.randomNumber(1, 100));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WorldIDWidget {...widgetProps} />
      </main>
    </div>
  );
};

export default Home;
