name: CI

on:
  - pull_request

jobs:
  lint:
    name: Source code formatting & spellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check formatting with Prettier
        working-directory: ./id
        run: yarn format:check

      - name: Spellcheck (entire repository)
        run: yarn spellcheck

  typecheck:
    name: Typecheck & linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint with ESLint
        working-directory: ./id
        run: yarn lint

      - name: Generate Kea typing
        working-directory: ./id
        run: yarn typegen

      - name: Check Typescript
        working-directory: ./id
        run: |
          yarn typecheck

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        working-directory: ./id
        run: yarn --frozen-lockfile

      - name: Run tests
        working-directory: ./id
        run: yarn test

  test-build:
    name: Test production build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        working-directory: ./id
        run: |
          yarn build
