name: CI

on:
  - pull_request

jobs:
  lint:
    name: Source code formatting & spellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        working-directory: ./id
        run: npm run format:check

      - name: Spellcheck (entire repository)
        run: npm run spellcheck

  typecheck:
    name: Typecheck & linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        working-directory: ./id
        run: npm run lint

      - name: Generate Kea typing
        working-directory: ./id
        run: npm run typegen

      - name: Check Typescript
        working-directory: ./id
        run: |
          npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies and run tests
        working-directory: ./id
        run: npm install-ci-test

  test-build:
    name: Test production build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        working-directory: ./id
        run: |
          npm run build
